server:
  port: 8763
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_forum?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: renjian50nian13
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    #stmp服务主机
    host: smtp.163.com
    #服务协议
    protocol: smtp
    #编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: leon19852070@163.com
    #授权码
    password: DHZPGYAMOIOJUDOJ
    test-connection: true
    properties:
      mail:
        stamp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl